### ISSUE TITLE
Very uncertain

### ISSUE THREAD

**Issue by prettyCoders** [aeternity/aepp-sdk-python#100]
![image](https://user-images.githubusercontent.com/36216120/50533116-6d4b6600-0b5e-11e9-98c9-2cb1f582138c.png)
![image](https://user-images.githubusercontent.com/36216120/50533122-7d634580-0b5e-11e9-86b8-f85cb1849831.png)

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/50533130-95d36000-0b5e-11e9-8e54-685a800707a0.png)

**Comment by noandrea** [comment]
Both are messages are related to connectivity problem to the node,
we could though make it more explicit in the first case.

**Comment by randomshinichi** [comment]
@prettyCoders we'd be interested to know what you use the `chain play` command for - I mean, the biggest reason you use it.
