### ISSUE TITLE
subprocess stdin does not work with input for Python CLI

### ISSUE THREAD

**Issue by randomshinichi** [aeternity/aepp-sdk-python#102]
Using `subprocess.run(stdin=....)`, the Python CLI never picks up the extra input, and thus fails the CLI interface tests, even though it behaves properly on an actual terminal.

**Comment by kryztoval** [comment]
I pass the data like this
`result = subprocess.run([pythonbin,aeclibin,"-u",epoch_url,"-d",epoch_dbg,"account","create",walletfile,"--password",password],stdout=subprocess.PIPE)`

does this help you?

**Comment by noandrea** [comment]
closing since not relevant anymore
