### ISSUE TITLE
Allow --force to skip interactive messages

### ISSUE THREAD

**Issue by kryztoval** [aeternity/aepp-sdk-python#105]
When requesting the private key from a script, there are some prompts that make it unusable, it would be great if there was an option you can use to prevent the command from stopping to ask for validation.

**Comment by noandrea** [comment]
Hi @kryztoval this is meant to be like this. 
In general exporting the private key unencrypted is a very bad thing and we don't want to encourage this type of usage.

**Comment by kryztoval** [comment]
I understand and I am not saying this should be removed. I am saying there should be a way to override this behavior. something like a "--insecure" or "--force" because this is an sdk and using it means you know what you are doing. So expecting it to always be used in an interactive manner seems counterproductive.

Right now I just modified my local installation to skip that prompt.

**Comment by noandrea** [comment]
late reply but you can use the script in this pr for this purpose:

https://github.com/aeternity/aepp-sdk-python/pull/226

**Comment by kryztoval** [comment]
This doesn't really solve it because I meant for a Way to use the the stock
python sdk as an interactive command line tool to control several wallets
and not for a way to use python or another script to maintain to do this. :(
