### ISSUE TITLE
Add base state channel functionality

### ISSUE THREAD

**Issue by noandrea** [aeternity/aepp-sdk-python#115]

**Comment by shekhar-shubhendu** [comment]
The Python SDK should implement the below methods as implemented by the js-sdk:

    - status => get channel current status
    - state => Get current state
    - update => Trigger an update
    - poi => Get proof of inclusion
    - balances => Get balances
    - leave => Leave channel
    - shutdown => Trigger a channel shutdown
    - sendMessage => Send generic message
    - withdraw => Withdraw tokens from the channel
    - deposit => Deposit tokens into the channel
    - createContract => Create a contract
    - callContract => Call a contract
    - callContractStatic => Call contract using dry-run
    - getContractCall => Get contract call result
    - getContractState => Get contract latest state
    - cleanContractCalls => Clean up all locally stored contract calls

(method name should be modified as per python standards)

### Refer to:

https://github.com/aeternity/aepp-sdk-js/tree/develop/es/channel
