### ISSUE TITLE
Add human readable amount formatting 

### ISSUE THREAD

**Issue by noandrea** [aeternity/aepp-sdk-python#162]
Add ability to format amounts in a human readable format

**Comment by kryztoval** [comment]
How do I disable this human readable formatting?

I really don't need it if I am using the python sdk as a tool to be called upon, did you guys add a flag for this behavior?

**Comment by noandrea** [comment]
It is enabled only for the "human readable" output format from the command line, 
where there are already other preprocessing made (for example the timestamps are converted to RFC3339 dates)
If you need the output of the command line in a "computer friendly" format you can use the `--json` flag that will produce json output with raw values

**Comment by kryztoval** [comment]
but processing the json was not as straight forward as the formatted result was since i only needed to get one line in the formatted output and the json is single lined.

**Comment by noandrea** [comment]
I strongly suggest to use the json output and a tool like [`jq`](https://stedolan.github.io/jq/) to fetch values for properties in an automated context using the command line client, for example:

get the balance of an account:
```
$ aecli inspect ak_REAu6DK8eqW5juKhGKTZo7svi1EcKxAsu7vq6yRUaNw4K6Ypg --json | jq '.balance?'
999916479999999900
```
get the sender, recipient and amount of a spend transaction:
```
$ aecli inspect th_GSkeoe3MGytHtNApk3KjqcxWVqa3rZF5U64NXpPvbg5bqwkZU --json | jq '.tx.sender_id?'
"ak_nv5B93FPzRHrGNmMdTDfGdd5xGZvep3MVSpJqzcQmMp59bBCv"


$ aecli inspect th_GSkeoe3MGytHtNApk3KjqcxWVqa3rZF5U64NXpPvbg5bqwkZU --json | jq '.tx.recipient_id?'
"ak_FMTrHVTxfW68a3WLxCk2Q94efDqmB1TgwY8bLVRVysVcqHtQT"

$ aecli inspect th_GSkeoe3MGytHtNApk3KjqcxWVqa3rZF5U64NXpPvbg5bqwkZU --json | jq '.tx.amount?'
3e+22
```
