### ISSUE TITLE
Error building with python 3.8 (cpython build error)

### ISSUE THREAD

**Issue by noandrea** [aeternity/aepp-sdk-python#275]
**Note: for support questions, please use the [forum](https://forum.aeternity.com)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

this is a consequence of this https://github.com/cython/cython/issues/2938 issue 

* **What is the current behavior?**
the sdk cannot be build using py 3.8 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

https://www.codepile.net/pile/G18eqM56

* **What is the expected behavior?**

* **Please tell us about your environment:**
  
  - SDK Version: v6.0.0
  - Python version: v3.8.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. forum, telegram, etc)

**Comment by shekhar-shubhendu** [comment]
current version of sdk `6.2.0` does not have this issue.
seems like it got resolved earlier when dependencies were upgraded.
please verify on your side too and close if all okay.
