### ISSUE TITLE
Incorrect string encoding by compiler.encode_calldata

### ISSUE THREAD

**Issue by mephinet** [aeternity/aepp-sdk-python#319]
Noob warning: I'm new to Aeternity, created my first contract yesterday and today I'm trying to interface with it using the Python SDK (after not having used Python for a decade).

For deploying the contract, I used `ContractNative` as outlined in https://aepp-sdk-python.readthedocs.io/en/stable/intro/tutorial02-contracts-deploy.html. I stored the contract's address, and am now trying to call one of its entrypoints `stateful entrypoint add_task(task_name: string)` using `Contract.call`. I realized that I need to use the `Compiler` to encode the `task_name` argument. My expectation would have been:
```compiler.encode_calldata(contract_src, "add_task", "try Python API" )```
but this fails with `OpenAPIClientException: Invalid contract`. When inspecting the exception, I see the error message from the compiler: `message': 'Unexpected identifier Python.\n'`.
To make it work, I need to double-escape the string like this:
```compiler.encode_calldata(contract_src, "add_task", "\"try Python API\"" )```
To me, this feels wrong, shouldn't this be handled by the SDK?

**To Reproduce**
1. Write a contract with an entrypoint with parameter
2. Try to encode its calldata using `compiler.encode_calldata`

**Expected behavior**
an encoded string

**Please tell us about your environment:**

  - docker, FROM python:3.8
  - with tha latest aepp-sdk installed via pip

**Comment by noandrea** [comment]
Hello @mephinet welcome to Aeternity (and welcome back to Python :)  
I will look into this issue, meanwhile can you try to use the `ContractNative` to call  the contract instead of using the lower level api? 
here is the tutorial how to do so https://aepp-sdk-python.readthedocs.io/en/stable/intro/tutorial02-contracts-call.html 
The process is exactly as for the deploying a contract but instead of callying `deploy` you will have to use the `at(CONTRACT_ID)` and then call the function as you would for a normal python object:
`contract_instance.add_task("try Python API")`

**Comment by mephinet** [comment]
Hi @noandrea, thank you very much for the hint! Indeed, using the generated methods make the call work as I would have expected it to do - probably because `convert_to_sophia` is called on all arguments, which does not happen in the scenario I was using at first.
Whether this is a bug or not is beyond my knowledge of the API - please feel free to close the issue if you feel I was mistaken...
Have a nice Sunday evening!

**Comment by shekhar-shubhendu** [comment]
Hi @mephinet, the `Compiler` interface has been kept dumb and it just passes the information as it is to the compiler attached and same goes for the `Contract` interface.
The `ContractNative` client uses the above two and provides the required transformations.

**Comment by noandrea** [comment]
closing now
