### ISSUE TITLE
How do I change my password?

### ISSUE THREAD

**Issue by kryztoval** [aeternity/aepp-sdk-python#74]
I mistakenly added spaces to my password and I find no way to replace my password.

**Comment by noandrea** [comment]
Currently there is no way to change the password for a keystore, what you can do is to re-save the private key:
```
aecli account address --private-key MYWALLET
Enter the account password []: 
!Warning! this will print your private key on the screen, are you sure? [y/N]: y
<account>
  Address ___________________________________________ ak_xxx
  Signing key _______________________________________  123456
</account>
```
and then 
```
aecli account save MYWALLETNEW 123456
Enter the account password []: 
<account>
  Address ___________________________________________ ak_xxx
  Path ______________________________________________ .../MYWALLETNEW
</account>

```

**Comment by kryztoval** [comment]
Wow. nice! I will try it.

**Comment by kryztoval** [comment]
Ok, this must be really wrong.

I made a test account: 
```
# ./aecli account create test.
ae
Enter the account password []:
<account>
  Address ___________________________________________ ak_hyFiqcX4sqGiNAo9ffmzZBR2hu3WDB6Dmc4yagN36C6yjeqiC
  Path ______________________________________________ /opt/aepp-sdk-python/
test.ae
</account>
```
I asked for the private key:
```
# ./aecli account address --private-key test.ae
Enter the account password []:
!Warning! this will print your private key on the screen, are you sure? [y/N]: y
<account>
  Address ___________________________________________ ak_hyFiqcX4sqGiNAo9ffmzZBR2hu3WDB6Dmc4yagN36C6yjeqiC
  Signing key _______________________________________ c6f424cfc15d7a97a66961fd2705d599f42fe8689381dd33f57b6328e9db7d8a5d06f39fa978c45a5ac553888c0b4e43783d8a36a67575153f727b2b8b2dab23
</account>
```

Since I have tried it before, and I know it ignores the bytes from 33 to 64, I tried recreating it using only the first part
```
./aecli account save test2.ae c6f424cfc15d7a97a66961fd2705d599f42fe8689381dd33f57b6328e9db7d8a
Enter the account password []:
<account>
  Address ___________________________________________ ak_hyFiqcX4sqGiNAo9ffmzZBR2hu3WDB6Dmc4yagN36C6yjeqiC
  Path ______________________________________________ /opt/aepp-sdk-python/test2.ae
</account>

```

And the result was this:
```
# ./aecli account save test2.ae c6f424cfc15d7a97a66961fd2705d599f42fe8689381dd33f57b6328e9db7d8a
Enter the account password []:
<account>
  Address ___________________________________________ ak_hyFiqcX4sqGiNAo9ffmzZBR2hu3WDB6Dmc4yagN36C6yjeqiC
  Path ______________________________________________ /opt/aepp-sdk-python/test2.ae
</account>

```

Is it right to ignore half of the signing key when recovering the account?
If you are wondering, if I ask it to tell me the private key of the test2.ae file, i get the same, original full key.

**Comment by noandrea** [comment]
Ed25519 keys are 64 bytes length, 32 for the seed (signing key) + 32 for the verifying key (publlic key).
But you only need the first 32 bytes to calculate the public key. The calculation of the public key is a relatively expensive operation, therefore is common to represent the Ed25519 in their expanded (32+32) bytes representation. 
You can find a more detailed explanation here: https://blog.mozilla.org/warner/2011/11/29/ed25519-keys/

**Comment by kryztoval** [comment]
So, from what I am hearing, should it be possible to recreate the address in the aepp-sdk-js with just the 32 bytes. Even if right now it requires 64bytes?
