### ISSUE TITLE
Spend is not working with the current release, returns invalid transaction

### ISSUE THREAD

**Issue by kryztoval** [aeternity/aepp-sdk-python#97]
Support requests with a tag that doesn't even exist?
That's just mean.

## Expected Behavior
Send transaction to succeed as it says in the documentation

## Current Behavior
It returns a `Error: Invalid transaction`

## Steps to Reproduce
- install the aepp-sdk-python
- create an account
- use a faucet to send you aettos
- try sending it to another account

## Environment / Context
ubuntu server 18.04.1
epoch v1.1.0 / docker aeternity/epoc:v1.1.0
aepps-sdk-python v1.1.2 / commit 302c8eca9b3422418d0ed3311ca7d62c00ec0cd6

**Comment by noandrea** [comment]
hi kryztoval,
if you are following the instructions on the readme, it is likely that you are not specifying the correct network_id. 

I will update the documentation to mention this step.

**Comment by kryztoval** [comment]
Could be. since I am trying the testnet and the edgenet right now.

**Comment by noandrea** [comment]
I've update the README with the network id for testnet. For `sdk-edgenet`  use `ae_devnet` as network id. 
Just be aware that we may dismiss sdk-edgenet and testnet is the preferred network for testing

**Comment by kryztoval** [comment]
Yeah, that fixed it, using the network id solved this issue
